config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :questions do
    resources :answers, shallow: true
  end

  resource :session, only: [:new, :create, :destroy]

  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#failure"
  get "/sign_out", to: "sessions#destroy"
  patch "/questions/:question_id/best_answer/:id", to: "questions#best_answer", as: :question_best_answer

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

	validates :description, presence: true, length: { minimum: 50,
    too_short: "must have at least %{count} characters."}
  validates :user_id, :question_id, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  belongs_to :user
  #belongs_to :user, class: User, foreign_key: :user_id
  belongs_to :best_answer, class: Answer, foreign_key: :best_answer_id

	validates :title, presence: true, length: { minimum: 40,
    too_short: "must have at least %{count} characters."}
  validates :description, presence: true, length: { minimum: 150,
    too_short: "must have at least %{count} characters."}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :questions
  has_many :answers

	validates :provider, :uid, :username, :url, presence: true

	def self.find_or_create_from_omniauth(auth)
    provider = auth.provider
    uid = auth.uid

    find_by(provider: provider, uid: uid) || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create(
      provider: auth.provider,
      uid: auth.uid,
      username: auth.info.nickname,
      url: auth.info.urls["Twitter"],
    )
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  # GET /answers
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  def show
    @answer = Answer.find(params[:id])
    @question = Question.find(params[:question_id])
  end

  # GET /answers/new
  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
  end

  # POST /answers
  def create
    @answer = Answer.new(answer_params)
    @question = Question.find(params[:question_id])

    if @answer.save
      redirect_to @question, notice: 'Your answer was submitted.'
    else

      render action: 'new'
    end
  end

  def destroy

  end

  def edit

  end

  def update

  end

  # GET /answers/search
  def search
    query = "%#{params[:query]}%"
    @answers = Answer
      .where('description like ?',
             query)
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def answer_params
    params.require(:answer).permit(:description, :question_id, :user_id, :submitter)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :user_signed_in?, :current_user, :same_user?

  protected
  def user_signed_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def set_current_user(user)
    @current_user = user
  end

  def same_user?(user)
    user.user_id == current_user.id
  end

  def authenticate!
    unless signed_in?
      flash[:notice] = 'You need to sign in if you want to do that!'

      redirect_to root_path
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # GET /questions
  def index
    @questions = Question.order(updated_at: :desc)
  end

  # GET /questions/1
  def show
    @question = Question.find(params[:id])
    @best_answer = @question.best_answer
    @answers = @question.answers.order(updated_at: :desc)

    if @answers.include?(@best_answer)
      @answers = @answers - [@best_answer]
      @answers.unshift(@best_answer)
    end
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # POST /questions
  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question has been submitted.'
    else
      render 'new'
    end
  end

  def edit
    @question = Question.find(params[:id])
    # @answers = Answer.find(:all)
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    Question.find(params[:id]).destroy
    redirect_to @question
  end

  def best_answer
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    # @question.best_answer = @answer
    if @question.update(best_answer_id: params[:id])
      redirect_to @question
    else
      flash[:notice] = "Error!"
      render @question
    end
  end

  # GET /questions/search
  def search
    query = "%#{params[:query]}%"
    @questions = Question
      .where('title like ? or description like ?',
             query, query)
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.require(:question).permit(:title, :description, :user_id, :submitter)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to "/auth/twitter"
  end

  def create
    user = User.find_or_create_from_omniauth(auth_hash)
    session[:user_id] = user.id
    set_current_user(user)
    flash[:notice] = "Successfully signed in as #{user.username}."

    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Signed out successfully."

    redirect_to root_path
  end


  def failure
    flash[:alert] = "Unable to sign in."

    redirect_to root_path
  end

  private

  def auth_hash
    request.env["omniauth.auth"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new

    Redcarpet::Markdown.new(renderer).render(text).html_safe
  end
end

app/helpers/session_helper.rb
module SessionHelper

end

app/views/answers/new.html.erb
<h1>Submit Your Answer</h1>

<h3>
  <%= @question.title %>
</h3>
<p>
  <%= @question.description %>
</p>

<% @answer.errors.full_messages.each do |message| %>
<%= message %>
<%end%>

<%if user_signed_in? %>
  <%= form_for @answer, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
    <%= f.label :description %>:<br />
    <%= f.text_area :description, size: "100x5" %><br />
    <%= f.hidden_field :question_id, value: @question.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "Submit" %>
  <% end %>
<% else %>
  <p>You must sign in to answer this question.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rescue Mission</title>
  <%= stylesheet_link_tag    "application", "normalize" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="top-bar">
  <div class="container">
    <a class="logo" href="/">Rescue Mission</a>
    <ul class="top-bar-section">
      <% if user_signed_in? %>
        <li>Signed in as @<%= current_user.username %></a></li>
        <li><a href="/sign_out">Sign out</a></li>
      <% else %>
        <li><a href="/auth/twitter">Sign in</a></li>
      <% end %>
    </ul>
  </div>
</div>

<% if flash.any? %>
  <div class="flash">
    <div class="container">
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<h1>Edit Your Question</h1>

<% @question.errors.full_messages.each do |message| %>
<%= message %>
<%end%>

<% if user_signed_in? && same_user?(@question) %>
  <%= form_for @question, url: {action: "update"}, html: {class: "nifty_form"} do |f| %>
    <%= f.label :title %>: <br />
    <%= f.text_field :title %><br />
    <%= f.label :description %>: </br />
    <%= f.text_area :description, size: "100x5" %><br />
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "Submit" %>
  <% end %>
  <%= button_to 'Delete Question', question_path(@question), method: :delete, data: {confirm: 'Are you sure?'} %>
<% else %>
  <p>You must sign in to edit your question.</p>
<% end %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<p>
  <%= button_to 'Add Question', new_question_path, method: :get %>
</p>

<br />

<ol>
  <% @questions.each do |question| %>
  <li>
    <%= question.created_at %> - <%= link_to question.title, question %>
  </li>
  <% end %>
</ol>

app/views/questions/new.html.erb
<h1>Submit Your Question</h1>

<% @question.errors.full_messages.each do |message| %>
<%= message %>
<%end%>

<%if user_signed_in? %>
  <%= form_for @question, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
    <%= f.label :title %>: <br />
    <%= f.text_field :title %><br />
    <%= f.label :description %>: <br />
    <%= f.text_area :description, size: "100x5" %><br />
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.submit "Submit" %>
  <% end %>
<% else %>
  <p>You must sign in to ask a question</p>
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<p>
  <%= markdown(@question.description) %>
</p>

<h2>Answers</h2>

<% @answers.each do |answer| %>
  <a href="<%= answer.user.url %>">@<%= answer.user.username %></a> at <%= answer.created_at %> said: <br />
  <%= markdown(answer.description) %><br />
  <% if user_signed_in? && same_user?(@question) %>


    <%= button_to "Mark Best Answer", question_best_answer_path(@question, answer), method: :patch %>
  <% end %>
  <br>
<% end %>

<% if user_signed_in? %>
  <%= button_to 'Answer Question', new_question_answer_path(@question), method: :get %>
<% end %>

<% if user_signed_in? && same_user?(@question) %>
  <%= button_to 'Edit Question', edit_question_path(@question), method: :get %>
  <%= button_to 'Delete Question', question_path(@question), method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>